apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acme-finance-ai-platform
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: acme-ai-demo.internal.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: acme-finance-ai-platform
                port:
                  number: 80
